name       : yakyak
version    : 1.3.2
release    : 4
source     :
    - https://github.com/yakyak/yakyak/releases/download/v1.3.2/yakyak-linux-x64.zip : 521785880751686bfbefc1898300ab5d6dabb9fe36f0e100adb10347cc09d484
license    : MIT
summary    : Desktop chat client for Google Hangouts
component  : network.im
description: |
    Desktop chat client for Google Hangouts
rundeps    :
    - gconf
    - libxscrnsaver
    - nodejs
install    : |
    yakDir=$installdir/%libdir%/yakyak
    cd $workdir
    install -dm755 $installdir/usr/bin
    install -dm755 $yakDir
    cp -R * $yakDir/
    ln -s %libdir%/yakyak/yakyak $installdir/usr/bin/yakyak
    install -Dm644 $pkgfiles/yakyak.desktop $installdir/usr/share/applications/yakyak.desktop
    install -Dm644 $pkgfiles/icon.png $installdir/usr/share/pixmaps/yakyak.png
    rm $yakDir/resources/app/icons/icon.png
    install -Dm644 $pkgfiles/icon.png $yakDir/resources/app/icons/icon.png
    for icon in $yakDir/resources/app/icons/icon@*.png; do
        rm $icon
        install -Dm644 $pkgfiles/icon.png $icon
    done
