name       : yakyak
version    : 1.4.2
release    : 7
source     :
    - https://github.com/yakyak/yakyak/releases/download/v1.4.2/yakyak-1.4.2-linux-x64.tar.gz : 09b76ec0e89d3a79bba794ccfebdb59e58418dc8d4eeb3e0ea000e3cf3f819a9
license    : MIT
summary    : Desktop chat client for Google Hangouts
component  : network.im
description: |
    Desktop chat client for Google Hangouts
rundeps    :
    - gconf
    - libxscrnsaver
    - nodejs
install    : |
    yakDir=$installdir/%libdir%/yakyak
    cd $workdir
    install -dm755 $installdir/usr/bin
    install -dm755 $yakDir
    cp -R * $yakDir/
    ln -s %libdir%/yakyak/yakyak $installdir/usr/bin/yakyak
    install -Dm644 $pkgfiles/yakyak.desktop $installdir/usr/share/applications/yakyak.desktop
    install -Dm644 $pkgfiles/icon.png $installdir/usr/share/pixmaps/yakyak.png
    rm $yakDir/resources/app/icons/icon.png
    install -Dm644 $pkgfiles/icon.png $yakDir/resources/app/icons/icon.png
    for icon in $yakDir/resources/app/icons/icon@*.png; do
        rm $icon
        install -Dm644 $pkgfiles/icon.png $icon
    done
