name       : yakyak
version    : 1.4.3
release    : 8
source     :
    - https://github.com/yakyak/yakyak/releases/download/v1.4.3/yakyak-1.4.3-linux-x64.tar.gz : 9b2614bf4b89afec131e68554ad41cf0c1e5808f59be43a5f3cc92cf6dd4c683
license    : MIT
summary    : Desktop chat client for Google Hangouts
component  : network.im
description: |
    Desktop chat client for Google Hangouts
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
rundeps    :
    - nodejs
install    : |
    yakDir=$installdir/%libdir%/yakyak
    cd $workdir
    install -dm755 $installdir/usr/bin
    install -dm755 $yakDir
    cp -R * $yakDir/
    ln -s %libdir%/yakyak/yakyak $installdir/usr/bin/yakyak
    install -Dm644 $pkgfiles/yakyak.desktop $installdir/usr/share/applications/yakyak.desktop
    install -Dm644 $pkgfiles/icon.png $installdir/usr/share/pixmaps/yakyak.png
    rm $yakDir/resources/app/icons/icon.png
    install -Dm644 $pkgfiles/icon.png $yakDir/resources/app/icons/icon.png
    for icon in $yakDir/resources/app/icons/icon@*.png; do
        rm $icon
        install -Dm644 $pkgfiles/icon.png $icon
    done
