name       : yakyak
version    : 1.5.1
release    : 11
source     :
    - https://github.com/yakyak/yakyak/releases/download/v1.5.1/yakyak-1.5.1-linux-x64.tar.gz : 83e655c58086d3e4b4b83d4923ef818cef293070536cc86bbbb06effe03280b9
license    : MIT
summary    : Desktop chat client for Google Hangouts
component  : network.im
description: |
    Desktop chat client for Google Hangouts
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-x11-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
install    : |
    yakDir=$installdir/%libdir%/yakyak
    cd $workdir
    install -dm00755 $installdir/usr/bin
    install -dm00755 $yakDir
    cp -R * $yakDir/
    ln -s %libdir%/yakyak/yakyak $installdir/usr/bin/yakyak
    install -Dm00644 $pkgfiles/yakyak.desktop $installdir/usr/share/applications/yakyak.desktop
    install -Dm00644 $pkgfiles/icon.png $installdir/usr/share/pixmaps/yakyak.png
    rm $yakDir/resources/app/icons/icon.png
    install -Dm00644 $pkgfiles/icon.png $yakDir/resources/app/icons/icon.png
    for icon in $yakDir/resources/app/icons/icon@*.png; do
        rm $icon
        install -Dm00644 $pkgfiles/icon.png $icon
    done
