name       : yakyak
version    : 1.4.0
release    : 6
source     :
    - https://github.com/yakyak/yakyak/releases/download/v1.4.0/yakyak-1.4.0-linux-x64.tar.gz : b7d741099d289c592725acf884330719e9a1fbc7ca7d19024868324f2997f688
license    : MIT
summary    : Desktop chat client for Google Hangouts
component  : network.im
description: |
    Desktop chat client for Google Hangouts
rundeps    :
    - gconf
    - libxscrnsaver
    - nodejs
install    : |
    yakDir=$installdir/%libdir%/yakyak
    cd $workdir
    install -dm755 $installdir/usr/bin
    install -dm755 $yakDir
    cp -R * $yakDir/
    ln -s %libdir%/yakyak/yakyak $installdir/usr/bin/yakyak
    install -Dm644 $pkgfiles/yakyak.desktop $installdir/usr/share/applications/yakyak.desktop
    install -Dm644 $pkgfiles/icon.png $installdir/usr/share/pixmaps/yakyak.png
    rm $yakDir/resources/app/icons/icon.png
    install -Dm644 $pkgfiles/icon.png $yakDir/resources/app/icons/icon.png
    for icon in $yakDir/resources/app/icons/icon@*.png; do
        rm $icon
        install -Dm644 $pkgfiles/icon.png $icon
    done
